script:
  - mkdir target
  - mkdir target/html
  - cp *.html target/html
  - cp -R css target/html
  - cp -R img target/html
  - cp -R js target/html
  - cp -R vendor target/html

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: "kiosk.world"
    skip_cleanup: true
    local_dir: target/html
    on:
      branch: master
