script:
  - mkdir target
  - cp -R * target/.
  - rm target/*.yml
  - rm -Rf target/.gitignore

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: "io.tchepannou.kribi"
    skip_cleanup: true
    local_dir: target/html
    on:
      branch: master
